# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert string to number
#'
#' M will be converted to -2
#' * (lost) will be converted to -3
#' N will be converted to -1
#'
#' @param x string
#' @return integer
#' @export
#' @useDynLib INORMUS, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @import tidyverse
parse_num_c <- function(x) {
    .Call(`_INORMUS_parse_num_c`, x)
}

